- name: Setup default alarms
  hosts: localhost
  vars:
    keystone_url: http://keystone:35357/v3
    keystone_user: monasca
    keystone_password: password
  roles:
    - {role: monasca-default-alarms, tags: [alarms]}
