- src: tkuhlman.monasca-ui
  name: monasca-ui
- src: tkuhlman.kafka
  name: kafka
- src: https://github.com/hpcloud-mon/ansible-influxdb
  name: influxdb
- src: tkuhlman.monasca-agent
  name: monasca-agent
- src: tkuhlman.monasca-api
  name: monasca-api
- src: https://github.com/hpcloud-mon/ansible-monasca-default-alarms
  name: monasca-default-alarms
- src: tkuhlman.monasca-notification
  name: monasca-notification
- src: tkuhlman.monasca-persister
  name: monasca-persister
- src: tkuhlman.monasca-schema
  name: monasca-schema
- src: tkuhlman.monasca-thresh
  name: monasca-thresh
- src: tkuhlman.percona
  name: percona
- src: tkuhlman.storm
  name: storm
- src: tkuhlman.zookeeper
  name: zookeeper
