---
# Some of this comes from https://github.com/dguerri/openstack-horizon
- name: Install horizon application and dependencies
  apt: name="{{ item }}" state=present install_recommends=no
  with_items:
    - apache2
    - memcached
    - libapache2-mod-wsgi
    - openstack-dashboard

- name: Configure keystone in horizon
  template: dest=/etc/openstack-dashboard/local_settings.py src=local_settings.py.j2 owner=root group=root mode=644

- name: Disable default apache config
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Setup root to be horizon
  lineinfile: dest=/etc/apache2/conf-enabled/openstack-dashboard.conf
              regexp=^WSGIScriptAlias
              line="WSGIScriptAlias / /usr/share/openstack-dashboard/openstack_dashboard/wsgi/django.wsgi"

- name: Run python manage.py compress for the dashboard
  command: python /usr/share/openstack-dashboard/manage.py compress
